import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Home, Users, BarChart3, LogOut, Search, ChevronRight, WalletCards, ClipboardPenLine, Save, CheckCircle2, ShieldCheck, RefreshCw } from 'lucide-react'
import { supabase } from './lib/supabase'
import { getCurrentBatch, getParticipants, getContributions, getMyProfile, getMyPermissions, saveSundayCollection } from './lib/crp'
import './styles.css'

const money = n => `₹${Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`
const dateLabel = s => new Date(`${s}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})
const today = () => new Date().toISOString().slice(0,10)
const isSunday = s => new Date(`${s}T00:00:00`).getDay() === 0

function Login({ onLogin }) {
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  async function submit(e){e.preventDefault();setBusy(true);setError('');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else onLogin(data.session);setBusy(false)}
  return <div className="login-shell"><div className="login-card"><div className="crest">✦</div><div className="eyebrow">CHRIST THE KING CHURCH</div><h1>Catechism Savings</h1><p className="muted">Sign in to view the current catechism savings fund.</p><form onSubmit={submit} className="form"><label>Username / email<input value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><p className="tiny">Access is controlled by your account permissions.</p></div></div>
}

function CollectionEntry({batch,people,existing,userId,canAdd,canEdit,onSaved}){
 const [date,setDate]=useState(today()),[amounts,setAmounts]=useState({}),[query,setQuery]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const existingMap=useMemo(()=>Object.fromEntries(existing.filter(x=>x.contribution_date===date).map(x=>[x.participant_id,x.amount])),[existing,date])
 useEffect(()=>{const next={};people.forEach(p=>{if(existingMap[p.id]!=null)next[p.id]=existingMap[p.id]});setAmounts(next);setMessage('')},[date,existingMap,people])
 const filtered=people.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())),total=Object.values(amounts).reduce((s,v)=>s+Number(v||0),0)
 async function save(){setMessage('');if(!isSunday(date)){setMessage('Choose a Sunday. Catechism contributions are recorded only on Sundays.');return}const changed=Object.keys(existingMap).some(id=>amounts[id]!==undefined&&Number(amounts[id])!==Number(existingMap[id]));if(changed&&!canEdit){setMessage('You can add new contributions, but only users with edit permission can change an existing entry.');return}setSaving(true);try{await saveSundayCollection({batchId:batch.id,date,userId,entries:people.map(p=>({participant_id:p.id,amount:amounts[p.id]||0}))});setMessage('Collection saved successfully.');await onSaved()}catch(e){setMessage(e.message)}finally{setSaving(false)}}
 return <div className="entry-page"><div className="page-title"><div><h1>Sunday Collection</h1><p>Enter contributions for {dateLabel(date)}.</p></div><ClipboardPenLine size={30} strokeWidth={1.4}/></div><div className="entry-toolbar"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="entry-total"><span>Entered</span><strong>{money(total)}</strong></div></div><div className="search"><Search size={18}/><input placeholder="Search participants…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="entry-list">{filtered.map(p=><div className="entry-row" key={p.id}><div className="avatar">{p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="person-info"><strong>{p.name}</strong><span>{existingMap[p.id]?`Saved: ${money(existingMap[p.id])}`:'No contribution recorded'}</span></div><div className="amount-input"><span>₹</span><input inputMode="numeric" value={amounts[p.id]??''} placeholder="0" onChange={e=>setAmounts(a=>({...a,[p.id]:e.target.value.replace(/[^0-9]/g,'')}))}/></div></div>)}</div>{message&&<div className={message.includes('successfully')?'success':'error'}>{message.includes('successfully')&&<CheckCircle2 size={16}/>} {message}</div>}<button className="primary sticky-save" onClick={save} disabled={saving||!isSunday(date)||(!canAdd&&!canEdit)}><Save size={18}/>{saving?'Saving…':'Save Sunday Collection'}</button></div>
}

function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[permissions,setPermissions]=useState([]),[tab,setTab]=useState('home'),[batch,setBatch]=useState(null),[people,setPeople]=useState([]),[contribs,setContribs]=useState([]),[loading,setLoading]=useState(true),[err,setErr]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(null)
 async function load(){setLoading(true);setErr('');try{const b=await getCurrentBatch();setBatch(b);const [p,c]=await Promise.all([getParticipants(b.id),getContributions(b.id)]);setPeople(p);setContribs(c);if(session){setProfile(await getMyProfile(session.user.id));setPermissions(await getMyPermissions(session.user.id))}}catch(e){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(session)load()},[session])
 const total=useMemo(()=>contribs.reduce((s,c)=>s+Number(c.amount),0),[contribs]),month=useMemo(()=>{const m=new Date().toISOString().slice(0,7);return contribs.filter(c=>c.contribution_date.startsWith(m)).reduce((s,c)=>s+Number(c.amount),0)},[contribs])
 const filtered=people.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())),isAdmin=profile?.role==='admin',canView=isAdmin||permissions.includes('crp.view_current_year'),canAdd=isAdmin||permissions.includes('crp.add_contributions'),canEdit=isAdmin||permissions.includes('crp.edit_contributions'),canCollect=canAdd||canEdit
 if(!session)return <Login onLogin={setSession}/>;if(loading)return <div className="loading"><div className="spinner"/>Loading savings data…</div>;if(!canView)return <div className="loading"><div className="error-panel"><h2>Access not configured</h2><p>Your account is signed in, but it does not yet have permission to view the current catechism batch.</p><p className="muted">Ask the administrator to enable <strong>crp.view_current_year</strong>.</p><button className="secondary" onClick={()=>supabase.auth.signOut()}><LogOut size={16}/> Sign out</button></div></div>;if(err)return <div className="loading"><div className="error-panel"><h2>Couldn’t load the savings data</h2><p>{err}</p><button className="secondary" onClick={load}><RefreshCw size={16}/> Try again</button></div></div>
 return <div className="app"><header className="topbar"><div><div className="eyebrow">CHRIST THE KING</div><strong>Catechism Savings</strong></div><div className="top-actions">{profile?.role&&<span className="role-pill"><ShieldCheck size={14}/>{profile.role}</span>}<button className="icon-btn" onClick={()=>supabase.auth.signOut()} title="Sign out"><LogOut size={18}/></button></div></header><main className="content">
 {tab==='home'&&<><section className="hero"><div><span className="pill">{batch?.year} · Current Batch</span><h1>Good to see you{profile?.full_name?`, ${profile.full_name.split(' ')[0]}`:''}.</h1><p>Here’s the latest view of the catechism savings fund.</p></div><WalletCards size={42} strokeWidth={1.3}/></section><div className="stats"><div className="stat primary-stat"><span>Total savings</span><strong>{money(total)}</strong><small>All recorded contributions</small></div><div className="stat"><span>This month</span><strong>{money(month)}</strong><small>{people.length} participants</small></div></div><section className="section"><div className="section-head"><h2>Quick access</h2></div>{canCollect&&<button className="action-card" onClick={()=>setTab('entry')}><div className="action-icon"><ClipboardPenLine size={21}/></div><div><strong>Sunday Collection</strong><span>Enter this week’s contributions</span></div><ChevronRight size={18}/></button>}<button className="action-card" onClick={()=>setTab('people')}><div className="action-icon"><Users size={21}/></div><div><strong>Participants</strong><span>View individual savings history</span></div><ChevronRight size={18}/></button><button className="action-card" onClick={()=>setTab('summary')}><div className="action-icon"><BarChart3 size={21}/></div><div><strong>Summary</strong><span>Recent collections and totals</span></div><ChevronRight size={18}/></button></section></>}
 {tab==='people'&&<section><div className="page-title"><div><h1>Participants</h1><p>{people.length} active participants in {batch?.year}.</p></div><Users size={30}/></div><div className="search"><Search size={18}/><input placeholder="Search participants…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="list">{filtered.map(p=><button className="person-row" key={p.id} onClick={()=>setSelected(p)}><div className="avatar">{p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="person-info"><strong>{p.name}</strong><span>{money(contribs.filter(c=>c.participant_id===p.id).reduce((s,c)=>s+Number(c.amount),0))} saved</span></div><ChevronRight size={18}/></button>)}</div></section>}
 {tab==='summary'&&<section><div className="page-title"><div><h1>Summary</h1><p>Contribution activity for {batch?.year}.</p></div><BarChart3 size={30}/></div><div className="summary-card"><WalletCards size={27}/><div><span>Total savings</span><strong>{money(total)}</strong></div></div><div className="section"><div className="section-head"><h2>Recent collections</h2></div>{[...new Set(contribs.map(c=>c.contribution_date))].sort().reverse().slice(0,8).map(d=><div className="collection-row" key={d}><span>{dateLabel(d)}</span><strong>{money(contribs.filter(c=>c.contribution_date===d).reduce((s,c)=>s+Number(c.amount),0))}</strong></div>)}</div></section>}
 {tab==='entry'&&<CollectionEntry batch={batch} people={people} existing={contribs} userId={session.user.id} canAdd={canAdd} canEdit={canEdit} onSaved={load}/>} </main><nav className="bottom-nav"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><Home/><span>Home</span></button><button className={tab==='people'?'active':''} onClick={()=>setTab('people')}><Users/><span>People</span></button><button className={tab==='summary'?'active':''} onClick={()=>setTab('summary')}><BarChart3/><span>Summary</span></button>{canCollect&&<button className={tab==='entry'?'active':''} onClick={()=>setTab('entry')}><ClipboardPenLine/><span>Collect</span></button>}</nav>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="sheet" onClick={e=>e.stopPropagation()}><button className="sheet-close" onClick={()=>setSelected(null)}>×</button><div className="avatar large">{selected.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><h2>{selected.name}</h2><div className="detail-total">{money(contribs.filter(c=>c.participant_id===selected.id).reduce((s,c)=>s+Number(c.amount),0))}</div><div className="history">{contribs.filter(c=>c.participant_id===selected.id).slice().reverse().map(c=><div className="history-row" key={c.id}><span>{dateLabel(c.contribution_date)}</span><strong>{money(c.amount)}</strong></div>)}</div></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App />)
